### ISSUE TITLE
Change in the Go toolchain 1.10 breaks the build.

### ISSUE THREAD

**Issue by aregm** [intel-go/nff-go#233]
This commit https://github.com/golang/go/commit/7dea509703eb5ad66a35628b12a678110fbb1f72 breaks the build.

**Comment by Quasilyte** [comment]
Build fails on all Go1.4+ versions with `-a` flag.
It does break on newer (1.10) even without `-a` build flag.

### Reason
NFF `make`-based Go build depends on the proper linkage (see below).
Go build may call linker (it does linking through `gcc` on linux)
on several object files. The exact combination depends on the
staleness and dependency resolving algorithms.
Those are changed in Go 1.10 significantly, hence build stopped to work.

NFF is so linkage-dependent due to `-Wl,--whole-archive` flag usage.
`go build` executes `gcc` with multiple copies of `CGO_LDFLAGS` (see `/mk/include.mk`),
and this leads to duplicate symbols:
```bash
# This is simplified command executed by cmd/link:
gcc obj1.o obj2.o \
  -Ldpdkpath \
  -Wl,--whole-archive -lrte_ring -lrte_mbuf -Wl,--no-whole-archive \
  -Ldpdkpath \
  -Wl,--whole-archive -lrte_ring -lrte_mbuf -Wl,--no-whole-archive
```
The main problem here is `-Wl,--whole-archive` around libraries.
Either there should be only one unique group inside them,
or it should not be used at all.

This simple example reproduces problem without NFF-specific stuff:
```bash
# Trivial program:
echo 'void main(int argc, char** argv) {}' > foo.c

# a) This builds OK:
gcc -o foo foo.c -lm -lm

# b) This causes multiple definitions errors:
gcc -o foo foo.c \
  -Wl,--whole-archive -lm -Wl,--no-whole-archive \
  -Wl,--whole-archive -lm -Wl,--no-whole-archive
```

(a) build successfully even though `-lm` passed twice (it could be `.a` file or `.o` - doesn't matter).
The only difference in (b) is both `-lm` wrapped inside `-Wl,--whole-archive`. This is exactly the case with NFF builds on Go1.10.

### Solution

The simplest solution is to avoid `-Wl,--whole-archive` if it's not needed.

> Note that it may require clean build. It's safer to run `go build` with `-a` flag during the first build or
> making other precautions to avoid cached artifacts usage.

The alternative solution is to re-structure build so that only one object file
depends on the dpdk directly. This can be hard to do in terms of `go build`,
but with `go tool compile` + `go tool link` there is a full control over the process.

Without `-Wl,--whole-archive` NFF builds successfully on Go1.10 and below
independently of `-a` flag.

### The patch

```diff
diff --git a/mk/include.mk b/mk/include.mk
index 29c486c..5f787e3 100644
--- a/mk/include.mk
+++ b/mk/include.mk
@@ -78,7 +78,6 @@ export CGO_LDFLAGS =          \
        -Wwrite-strings                         \
        -Wl,--no-as-needed                      \
        -Wl,-export-dynamic                     \
-       -Wl,--whole-archive                     \
        -lrte_distributor                       \
        -lrte_reorder                           \
        -lrte_kni                               \
@@ -122,8 +121,7 @@ export CGO_LDFLAGS =        \
        -ldl                                    \
        -lnuma                                  \
        -lrte_mempool_ring                      \
-       -Wl,--end-group                         \
-       -Wl,--no-whole-archive
+       -Wl,--end-group

 # Universal check whether a variable is set
 .PHONY: .check-defined-%
 ```

**Comment by gshimansky** [comment]
Yes this solution does help to successfully build executables, but when running them I get an unexpected error that doesn't happen with --whole-archive switch:
```------------***------ Filling FlowFunctions ------***------------
MBUF: error setting mempool handler
EAL: Error - exiting with code: 1
  Cause: Cannot create mbuf pool
```
It is not clear exactly what causes this error and needs additional investigation.

**Comment by Quasilyte** [comment]
I think this is not very Go-specific issue as it's easily reproducible in C (gcc).

The best think I could try is to figure out why `go build` includes several objects that are linked with `dpdk`. This may not resolve into go tool fix because NFF is somewhat special Go project that in a way it's build process works.

@gshimansky, any suggestions?

**Comment by gshimansky** [comment]
Yes, it would be good to figure out why there are multiple references to `CGO_LDFLAGS ` in linking command line. From what I could find, --whole-archive is often used to [link constructors that are not directly referenced by the executable](https://stackoverflow.com/a/842770/4584975), and DPDK build does require to use it when linking PMD drivers statically [(here1)](http://dpdk.org/dev/patchwork/patch/2184/), [(here2)](https://dpdk.org/dev/patchwork/patch/32177/) for this whole reason.

So it seems that we need to keep --whole-archive in NFF-Go build.

**Comment by Quasilyte** [comment]
> it would be good to figure out why there are multiple references to CGO_LDFLAGS in linking command line

It just forwards `-Wl` flags to the linker. The unanswered part is why single executable requires several objects that carry `-Wl` flag sets (that are incompatible when duplicated). Or, put differently: why it sometimes does require multiple such objects (with `-a`) and the other times it don't (without `-a` on older releases). It could be related to Go incremental build mechanisms (requires investigation).

I have few thoughts that may help to understand situation a little better.
Will report later.

**Comment by gshimansky** [comment]
Yes, my question was exactly about why duplication happens for flags mentioned in `CGO_LDFLAGS`. If it is possible to overcome duplication with calling `go tool compile` and `go tool link` manually, we could use this approach.

**Comment by Quasilyte** [comment]
Oh my.
That was almost obvious.
All CGO packages receive same set of flags. 
This is OK if flags do not interfere with each other, but if they do, bad things going to happen.

Everything below is for Go 1.9. 
I have yet to check Go 1.10, but I think most things stay true.

Suppose we are building `test/stability/testResend` with `-a` flag.
This tells Go to re-compile all dependencies.
It turns out that there are three CGO packages that `testResend` depend on:
- `low` from NFF
- `net` from stdlib
- `runtime/cgo` from stdlib

Each such dependency brings all our flags:
```
ldobj>>>> net; file="/tmp/go-build210119133/net.a"
--------- cgoflags: -L/home/quasilyte/CODE/intel/yanff_get/src/github.com/intel-go/nff-go/dpdk/dpdk-17.08/x86_64-native-linuxapp-gcc/lib
--------- cgoflags: -W
--------- cgoflags: -Wall
--------- cgoflags: -Werror
--------- cgoflags: -Wstrict-prototypes
--------- cgoflags: -Wmissing-prototypes
--------- cgoflags: -Wmissing-declarations
--------- cgoflags: -Wold-style-definition
--------- cgoflags: -Wpointer-arith
--------- cgoflags: -Wcast-align
--------- cgoflags: -Wnested-externs
--------- cgoflags: -Wcast-qual
--------- cgoflags: -Wformat-nonliteral
--------- cgoflags: -Wformat-security
--------- cgoflags: -Wundef
--------- cgoflags: -Wwrite-strings
--------- cgoflags: -Wl,--no-as-needed
--------- cgoflags: -Wl,-export-dynamic
--------- cgoflags: -Wl,--whole-archive
--------- cgoflags: -lrte_distributor
--------- cgoflags: -lrte_reorder
--------- cgoflags: -lrte_kni
... other flags
--------- cgoflags: -Wl,--end-group
--------- cgoflags: -Wl,--no-whole-archive

... same for "runtime/cgo" and "low"
```
GCC is executed like this:
```
gcc \
    -m64 -gdwarf-2 -o $WORK/command-line-arguments/_obj/exe/a.out -rdynamic \
    /tmp/go-link-924645439/go.o \
    /tmp/go-link-924645439/000000.o \ # low
    /tmp/go-link-924645439/000001.o \ # net
    /tmp/go-link-924645439/000002.o \ # runtime/cgo
    -L/home/quasilyte/CODE/intel/yanff_get/src/github.com/intel-go/nff-go/dpdk/dpdk-17.08/x86_64-native-linuxapp-gcc/lib -W -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-align -Wnested-externs -Wcast-qual -Wformat-nonliteral -Wformat-security -Wundef -Wwrite-strings -Wl,--no-as-needed -Wl,-export-dynamic -Wl,--whole-archive -lrte_distributor -lrte_reorder -lrte_kni -lrte_pipeline -lrte_table -lrte_port -lrte_timer -lrte_hash -lrte_jobstats -lrte_lpm -lrte_power -lrte_acl -lrte_meter -lrte_sched -lrte_vhost -Wl,--start-group -lrte_kvargs -lrte_mbuf -lrte_ip_frag -lrte_ethdev -lrte_mempool -lrte_ring -lrte_eal -lrte_cmdline -lrte_cfgfile -lrte_pmd_bond -lrte_pmd_vmxnet3_uio -lrte_net -lrte_pmd_virtio -lrte_pmd_cxgbe -lrte_pmd_enic -lrte_pmd_i40e -lrte_pmd_fm10k -lrte_pmd_ixgbe -lrte_pmd_e1000 -lrte_pmd_ring -lrte_pmd_af_packet -lrte_pmd_null -lrt -lm -ldl -lnuma -lrte_mempool_ring -Wl,--end-group -Wl,--no-whole-archive \
    -L/home/quasilyte/CODE/intel/yanff_get/src/github.com/intel-go/nff-go/dpdk/dpdk-17.08/x86_64-native-linuxapp-gcc/lib -W -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-align -Wnested-externs -Wcast-qual -Wformat-nonliteral -Wformat-security -Wundef -Wwrite-strings -Wl,--no-as-needed -Wl,-export-dynamic -Wl,--whole-archive -lrte_distributor -lrte_reorder -lrte_kni -lrte_pipeline -lrte_table -lrte_port -lrte_timer -lrte_hash -lrte_jobstats -lrte_lpm -lrte_power -lrte_acl -lrte_meter -lrte_sched -lrte_vhost -Wl,--start-group -lrte_kvargs -lrte_mbuf -lrte_ip_frag -lrte_ethdev -lrte_mempool -lrte_ring -lrte_eal -lrte_cmdline -lrte_cfgfile -lrte_pmd_bond -lrte_pmd_vmxnet3_uio -lrte_net -lrte_pmd_virtio -lrte_pmd_cxgbe -lrte_pmd_enic -lrte_pmd_i40e -lrte_pmd_fm10k -lrte_pmd_ixgbe -lrte_pmd_e1000 -lrte_pmd_ring -lrte_pmd_af_packet -lrte_pmd_null -lrt -lm -ldl -lnuma -lrte_mempool_ring -Wl,--end-group -Wl,--no-whole-archive \
    -L/home/quasilyte/CODE/intel/yanff_get/src/github.com/intel-go/nff-go/dpdk/dpdk-17.08/x86_64-native-linuxapp-gcc/lib -W -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-align -Wnested-externs -Wcast-qual -Wformat-nonliteral -Wformat-security -Wundef -Wwrite-strings -Wl,--no-as-needed -Wl,-export-dynamic -Wl,--whole-archive -lrte_distributor -lrte_reorder -lrte_kni -lrte_pipeline -lrte_table -lrte_port -lrte_timer -lrte_hash -lrte_jobstats -lrte_lpm -lrte_power -lrte_acl -lrte_meter -lrte_sched -lrte_vhost -Wl,--start-group -lrte_kvargs -lrte_mbuf -lrte_ip_frag -lrte_ethdev -lrte_mempool -lrte_ring -lrte_eal -lrte_cmdline -lrte_cfgfile -lrte_pmd_bond -lrte_pmd_vmxnet3_uio -lrte_net -lrte_pmd_virtio -lrte_pmd_cxgbe -lrte_pmd_enic -lrte_pmd_i40e -lrte_pmd_fm10k -lrte_pmd_ixgbe -lrte_pmd_e1000 -lrte_pmd_ring -lrte_pmd_af_packet -lrte_pmd_null -lrt -lm -ldl -lnuma -lrte_mempool_ring -Wl,--end-group -Wl,--no-whole-archive \
    -lpthread -no-pie
```
Note three `-L` sets.

### Conclusion

CGO flags should be idempotent. If they can affect and/or break other object in unintended way, `go build` may not be the right tool. I almost sure that this is expected behavior, CGO flags are not namespaced after all, they are shared for all packages with `import "C"`.

Our problem is that `-Wl,--whole-archive` makes CGO flags have side effects: it's invalid to repeat them for a single `gcc` invocation.

**Comment by Quasilyte** [comment]
It's strange that CGO flags are repeated.
I wonder if this behavior is ever useful. 
Maybe it is a bug after all?
Need to see 1.10 and some more time to do better conclusions.

**Comment by aregm** [comment]
Using go tool compile and link can be considered as a workaround, but not a final solution. We should be able to use standard go build.

**Comment by Quasilyte** [comment]
The CGO_LDFLAGS environment variable is added "as is" (unchecked) to all
package-specific `#cgo LDFLAGS` options.

If `-Wl,--whole-archive` and `-Wl,--no-whole-archive` linker flags were
whitelisted in compiler, we could include package-specific LDFLAGS for `low` package.
This prevents flags to be duplicated per each CGO object file (object files are in
gc compiler own format).

We could send a change in Go that adds `re("-Wl,--(no-)?whole-archive")` to
`validLinkerFlags` variable in `cmd/go/internal/work/security.go`.

I can try experimenting with two-stage build, too.

**Comment by Quasilyte** [comment]
ld;dr: temporary fix is to use `CGO_CXXFLAGS_ALLOW=".*" CGO_LDFLAGS_ALLOW=".*" CGO_CFLAGS_ALLOW=".*"`
(the regexp can be set to allow required flags).

See: https://github.com/golang/go/wiki/InvalidFlag.

As for "Why linker duplicates flags?":
The `CGO_LDFLAGS` environment variable is added "as is" (unchecked) to all
package-specific `#cgo LDFLAGS` options.

If `-Wl,--whole-archive` and `-Wl,--no-whole-archive` linker flags were
whitelisted in the compiler, we could include package-specific LDFLAGS for `low` package.
This prevents flags to be duplicated per each CGO object file (object files are in
gc compiler own format).

I believe this issue can be used to report missing whitelist pattern:
https://github.com/golang/go/issues/23749.

**Comment by Quasilyte** [comment]
Example patch (you may want to fix this problem in different way, it's just and example):
```diff
diff --git a/low/low.go b/low/low.go
index 702a993..38b9173 100644
--- a/low/low.go
+++ b/low/low.go
@@ -5,6 +5,7 @@
 package low
 
 /*
+#cgo LDFLAGS: -Wl,--whole-archive -lrte_distributor -lrte_reorder -lrte_kni -lrte_pipeline -lrte_table -lrte_port -lrte_timer -lrte_hash -lrte_jobstats -lrte_lpm -lrte_power -lrte_acl -lrte_meter -lrte_sched -lrte_vhost -Wl,--start-group -lrte_kvargs -lrte_mbuf -lrte_ip_frag -lrte_ethdev -lrte_mempool -lrte_ring -lrte_eal -lrte_cmdline -lrte_cfgfile -lrte_pmd_bond -lrte_pmd_vmxnet3_uio -lrte_net -lrte_pmd_virtio -lrte_pmd_cxgbe -lrte_pmd_enic -lrte_pmd_i40e -lrte_pmd_fm10k -lrte_pmd_ixgbe -lrte_pmd_e1000 -lrte_pmd_ring -lrte_pmd_af_packet -lrte_pmd_null -lrt -lm -ldl -lnuma -lrte_mempool_ring -Wl,--end-group -Wl,--no-whole-archive
 #include "low.h"
 */
 import "C"
diff --git a/mk/include.mk b/mk/include.mk
index 29c486c..5e06924 100644
--- a/mk/include.mk
+++ b/mk/include.mk
@@ -76,54 +76,8 @@ export CGO_LDFLAGS =				\
 	-Wformat-security			\
 	-Wundef					\
 	-Wwrite-strings				\
-	-Wl,--no-as-needed			\
-	-Wl,-export-dynamic			\
-	-Wl,--whole-archive			\
-	-lrte_distributor			\
-	-lrte_reorder				\
-	-lrte_kni				\
-	-lrte_pipeline				\
-	-lrte_table				\
-	-lrte_port				\
-	-lrte_timer				\
-	-lrte_hash				\
-	-lrte_jobstats				\
-	-lrte_lpm				\
-	-lrte_power				\
-	-lrte_acl				\
-	-lrte_meter				\
-	-lrte_sched				\
-	-lrte_vhost				\
-	-Wl,--start-group			\
-	-lrte_kvargs				\
-	-lrte_mbuf				\
-	-lrte_ip_frag				\
-	-lrte_ethdev				\
-	-lrte_mempool				\
-	-lrte_ring				\
-	-lrte_eal				\
-	-lrte_cmdline				\
-	-lrte_cfgfile				\
-	-lrte_pmd_bond				\
-	-lrte_pmd_vmxnet3_uio			\
-	-lrte_net				\
-	-lrte_pmd_virtio			\
-	-lrte_pmd_cxgbe				\
-	-lrte_pmd_enic				\
-	-lrte_pmd_i40e				\
-	-lrte_pmd_fm10k				\
-	-lrte_pmd_ixgbe				\
-	-lrte_pmd_e1000				\
-	-lrte_pmd_ring				\
-	-lrte_pmd_af_packet			\
-	-lrte_pmd_null				\
-	-lrt					\
-	-lm					\
-	-ldl					\
-	-lnuma					\
-	-lrte_mempool_ring			\
-	-Wl,--end-group				\
-	-Wl,--no-whole-archive
+	-Wl,--no-as-needed 			\
+	-Wl,-export-dynamic
 
 # Universal check whether a variable is set
 .PHONY: .check-defined-%
diff --git a/mk/leaf.mk b/mk/leaf.mk
index fb3cd1d..a072d55 100644
--- a/mk/leaf.mk
+++ b/mk/leaf.mk
@@ -10,7 +10,7 @@ include $(PATH_TO_MK)/include.mk
 # Build all
 .PHONY: clean
 $(EXECUTABLES) : % : %.go
-	go build $< $(COMMON_FILES)
+	CGO_LDFLAGS_ALLOW='-Wl,--(no-)?whole-archive' go build -a $< $(COMMON_FILES)
 # Use the following line to build Go files without optimizations
 #	go build -gcflags '-N -l' $< $(COMMON_FILES)
 ```

**Comment by gshimansky** [comment]
With integrated pull request #243 this bug should be resolved.
